<?php
echo '<!DOCTYPE html>';
echo '<html>';
echo '<head>';
echo '<title>Registration</title>';
echo '</head>';
echo '<body>';
echo '<form action="form.php" method="post">';
echo '<h2>Registration</h2>';
echo '<table>';
echo '<td>';
echo '<fieldset>';
echo '<legend>General Information</legend>';
echo '<table>';
echo '<label for="fname">First Name:</label>';
echo '<input type="text" id="fname" name="fname" value= "Tamim"><br><br>';
echo '';
echo '<label for="lname">Last Name:</label>';
echo '<input type="text" id="lname" name="lname" value="Hasan Apurbo"><br><br>';
echo '';
echo '';
echo '<p><strong>Gender :</strong>';
echo '<input type="radio" id="html" name="Gender" value="Male"';
echo '<label for="Male" >Male</label>';
echo '<input type="radio" id="css" name="Gender" value="Female"';
echo '<label for="Female" >Female</label><br></p><br>';
echo '';
echo '<label for="fname">Father Name:</label>';
echo '<input type="text" id="fname" name="fname" value="Helel"><br><br>';
echo '';
echo '<label for="fname">Mother name:</label>';
echo '<input type="text" id="fname" name="fname" value="Taslima"><br><br>';
echo '';
echo '';
echo '<label for="bloodgroup">Blood Group:</label>';
echo '<select id="bloodgroup" name="bloodgroup">';
echo '<option value="a+">A+</option>';
echo '<option value="b+">B+</option>';
echo '<option value="ab+">AB+</option>';
echo '<option value="o+">O+</option>';
echo '</select><br><br>';
echo '';
echo '';
echo '<label for="religion">Religion:</label>';
echo '<select id="religion" name="religion">';
echo '<option value="islam">Islam</option>';
echo '<option value="hinduism">Hinduism</option>';
echo '<option value="buddhim">Buddhim</option>';
echo '</select><br><br>';
echo '';
echo '</table>';
echo '</fieldtext>';
echo '</td>';
echo '';
echo '<td>';
echo '<fieldset>';
echo '<legend>Contact Information</legend>';
echo '<table>';
echo '';
echo '<label for="fname">Email:</label>';
echo '<input type="text" id="fname" name="fname" value= "tamimhasanapurbo102"><br><br>';
echo '';
echo '<label for="lname">Phone/Mobile</label>';
echo '<input type="text" id="lname" name="lname" value=+880-01637241089><br><br>';
echo '';
echo '<label for="fname">Website:</label>';
echo '<input type="text" id="fname" name="fname" value= "https://tamim.me"><br><br>';
echo '';
echo '<p><b>Present Address :</b><fildset><legend>Present Address</legend>';
echo '<select> <option value="bangladesh">Bangladesh</option>';
echo '<option value="india">India</option>';
echo '<option value="pakistan">Pakistan</option>';
echo '</select>';
echo '';
echo '<select> <option value="dhaka">Dhaka</option>';
echo '<option value="dilli">Dilli</option>';
echo '<option value="islamabad">Islamabad</option>';
echo '</select>';
echo '</p>';
echo '';
echo '<p><input type="text" style="width:80px; height: 50px"><br></p>';
echo '<p><input type="number"><br></p>';
echo '';
echo '</fildset>';
echo '</table>';
echo '</fieldset>';
echo '</td>';
echo '';
echo '';
echo '<td>';
echo '<fieldset>';
echo '<legend>Account Information</legend>';
echo '<table>';
echo '<label for="username">Username:</label>';
echo '<input type="text" id="username" name="username" value= "tamim"><br><br>';
echo '';
echo '<label for="pwd">Password:</label>';
echo '<input type="password" id="pwd" name="pwd"><br><br>';
echo '';
echo '<label for="pwd">Confirm Password:</label>';
echo '<input type="password" id="pwd" name="pwd"><br><br>';
echo '';
echo '</table>';
echo '</fieldset>';
echo '<input type="submit" value="Register"><br><br>';
echo '';
echo '';
echo '</td>';
echo '</table>';
echo '</form>';
echo '</body>';
echo '</html>';
?>